// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32            `json:"id"`
	Username  pgtype.Text      `json:"username"`
	Password  pgtype.Text      `json:"password"`
	Avatar    pgtype.Text      `json:"avatar"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}
